### ISSUE TITLE
add "Try It"

### ISSUE THREAD

**Issue by sinzone** [Mashape/getkong.org#82]
Terminal simulator with an interactive tutorial to learn the basics of Kong. 

Example: https://www.docker.com/tryit/

**Comment by sinzone** [comment]
@Nijikokun what's the name of that tool that does virtual terminals in the browser?

**Comment by Nijikokun** [comment]
There are quite a few:

- http://www.erikosterberg.com/terminaljs/
- http://terminal.jcubic.pl/
- http://gottox.de/terminal.js/

**Comment by ahmadnassri** [comment]
will be very tricky for us, since we have an API for admin control, meaning parsing and mimicking cURL commands ... (vs. docker is pre-set cli commands)

better to use http://runnable.com/ and embed on site for an interactive setup with a REAL Kong instance ...

**Comment by ahmadnassri** [comment]
here you go: http://runnable.com/VVVzgrrneBwFOSnA/

**Comment by rainum** [comment]
Thanks @ahmadnassri! Can you tell me how can I embed this terminal window? Only with iframe or there is proper way to do this?

@sinzone where should we place this tutorial? Maybe I should create separate docs section for it like http://take.ms/MKqae?

**Comment by ahmadnassri** [comment]
with runnable.com there doesn't seem to be an embed function, and it seems to be the same session / server for everyone ... perhaps pointing people there is one way to do it, they can fork and create their own instance.

**Comment by sinzone** [comment]
"Try It" it's the header bar and it's a new page. not in the doc. 

runnable is nice but too bad doesn't have embedded feature and unique sessions. so, we need to go back to terminal emulators and just show a subset of feature, excluding API admin.

**Comment by ahmadnassri** [comment]
but there are no features without the admin API ... all you can do is "start" and "stop"

**Comment by thibaultCha** [comment]
Well there is a PR to manipulate the data from the CLI too. It was not included in 0.3 but could have, we talked about it...

**Comment by ahmadnassri** [comment]
if we get full control from the CLI, then we can build a faux terminal and use that for demos .... still a lot of work to mock everything vs. a real instance ...

**Comment by rainum** [comment]
Ok, I think we should wait until Kong 0.3 is released. We will see than what we can do.

**Comment by shashiranjan84** [comment]
we can try to put TRY IT which is a link to Runnable.

**Comment by ahmadnassri** [comment]
closed with 9e18deb4c16a9118099cf8c376059df14353df75

**Comment by montanaflynn** [comment]
When I go to to runnable I try to use the terminal in the bottom (not clicking Run) and it doesn't work because that container and port is no longer running.

There's also another bug in the demo, you need to add a `sleep 5` in main.sh between the request and starting Kong since the container won't be running by the time the script starts kong.

The biggest problem with sending people directly to runnable is it has no associated tutorial so it loses any benefit of teaching or showcasing functionality.

I have a full Kong demo available powered by docker + term.js that's online here for now: http://trykong.cloudbrain.io/, we can get a new domain or point a subdomain to it like `demo.getkong.org`. 

Once `0.3.0` drops I'll update the image and we can switch it out for runnable. I wrote a [small guide](https://gist.github.com/montanaflynn/2beb2a49e464e1821cad) that I think is quicker and IMO a better showcase of Kong than the current 5 minute quickstart guide which we could use specifically for this purpose. My demo image also includes jq and siege so people can really play around with Kong, I also have it exposed to the public (try `echo $HOST` in the demo) but kong doesn't support wildcard subdomains yet (https://github.com/Mashape/kong/issues/297) and honestly it might be better to not allow outside access for these purposes.

I'd like to create a special page with the tutorial so it looks more like this (removing sidebar, making terminal responsive by moving from side to bottom on smaller screens)

![screen shot 2015-06-03 at 7 45 06 pm](https://cloud.githubusercontent.com/assets/24260/7975921/18a72880-0a29-11e5-915c-81d6bcb2a3cc.png)

![screen shot 2015-06-03 at 7 47 30 pm](https://cloud.githubusercontent.com/assets/24260/7975951/73041f54-0a29-11e5-8edd-2bb743ebd243.png)

**Comment by ahmadnassri** [comment]
@montanaflynn the runnable example was never meant to be used for this, @sinzone put it on afterwards as a temp. 

you would have know this, and have the full context if you were around...

**Comment by montanaflynn** [comment]
Alright then let's reopen this issue.

My demo with the guide and kong terminal loads super slow compared to [trykong.cloudbrain.io:8080](http://trykong.cloudbrain.io:8080) which doesn't support copy + paste. The javascript is built with browserify and is huge (2+ mb) so it might be best to preload it on getkong.org. I'm waiting for 0.3.0 to come out so I can add a cache header using response transformation plugin which will make preloading a viable option. 

Will get it on GitHub soon, just a lot of moving pieces (website, custom docker image, docker server, etc...) but it's based off https://github.com/maxogden/adventure-time

**Comment by ahmadnassri** [comment]
closing this in favor of upcoming Kong Cloud service
